// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEjd89UJZokslno8LhOU3ycKnWskjNng',
    appId: '1:811187025225:web:69a36f340ba16f19861698',
    messagingSenderId: '811187025225',
    projectId: 'detailing-app-jrf',
    authDomain: 'detailing-app-jrf.firebaseapp.com',
    storageBucket: 'detailing-app-jrf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAgri5I-uUL1nT3lBfZHLxgXy1Sm2bYO0',
    appId: '1:811187025225:android:a70e0d6f96aac807861698',
    messagingSenderId: '811187025225',
    projectId: 'detailing-app-jrf',
    storageBucket: 'detailing-app-jrf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2nMwomAGyZ9gYz-Qkzq2XZ1wkX7tiCc',
    appId: '1:811187025225:ios:c84dc5e98c572d51861698',
    messagingSenderId: '811187025225',
    projectId: 'detailing-app-jrf',
    storageBucket: 'detailing-app-jrf.appspot.com',
    iosClientId: '811187025225-727g330jsjk2de6kn8772o4upvqp6h5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.detailingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK2nMwomAGyZ9gYz-Qkzq2XZ1wkX7tiCc',
    appId: '1:811187025225:ios:c84dc5e98c572d51861698',
    messagingSenderId: '811187025225',
    projectId: 'detailing-app-jrf',
    storageBucket: 'detailing-app-jrf.appspot.com',
    iosClientId: '811187025225-727g330jsjk2de6kn8772o4upvqp6h5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.detailingApp',
  );
}
